// The libraries this deployment bundles, as the blueprint build checks pins against them: each
// library's name mapped to the names of the libraries it imports. Read from the generated module
// scripts/build-gadget-libraries.ts writes, since a library's imports are found while bundling it.
//
// Loaded on demand rather than imported statically, because the module is build output
// (gitignored, so absent on a clean checkout) and the failure should say what to run rather than
// surface as an unresolved-module stack.

import { access } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const GENERATED_MODULE = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "generated",
    "gadget-libraries.ts");

export async function loadBundledLibraries(): Promise<Map<string, readonly string[]>> {
  try {
    await access(GENERATED_MODULE);
  } catch (err) {
    throw new Error(`${GENERATED_MODULE} is missing: it is generated by ` +
        `scripts/build-gadget-library-types.ts and scripts/build-gadget-libraries.ts, in that ` +
        `order, which have to run before the format blueprints build.`, { cause: err });
  }
  const { GADGET_LIBRARIES } = await import("../src/generated/gadget-libraries.ts");
  return new Map(GADGET_LIBRARIES.map(library => [library.name, library.dependencies]));
}
